name: Suporte Distros Linux BR - Notícias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 17 * * *'
    - cron: '0 23 * * *'

jobs:
  publicar-noticias:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar robô de notícias
        env:
          # Blogger
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}

          # Gemini
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          # Configurações do Blog
          BLOG_NAME: "Suporte Distros Linux BR"
          BLOG_HOME_URL: "https://suportedistroslinuxbr.blogspot.com"

        run: python -u bot/main.py
